site_name: ATPL Notes
nav:
  - Home: index.md
  - Instruments:
      - Principles and Sensors: Instruments/principles-and-sensors.md
      - Pressure and Sensing: Instruments/pressure-sensing.md
      - Pressure Altimeters: Instruments/pressure-altimeters.md
      - Vertical Speed Indicators: Instruments/vertical-speed-indicators.md
      - Airspeed Indication: Instruments/airspeed-indication.md
      - Machmeters and ADCs: Instruments/machmeter.md
  - Human Performance:
      - Basic Concepts: Human-Performance/basic-concepts.md
  - Utilities:
      - Utilities: Utilities/Utilities.md
theme:
  name: material

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.4/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.4/contrib/auto-render.min.js
  - js/math.js

